#! /bin/tcsh -f
#By Weiting Zhang, July 10,2020

#Used to find the missing points of spectrum data from Ocean View spectrometers
#Input: the raw text file of the spectrum data
#Output: will be two columns of numbers. 
#the first number is the time point that the missng data happened
#the last number is the total number of time points

# e.g. find_miss_points  Subj1_Stim1.txt Subj1_Stim1_misspoints.txt

set file = $1
set output = $2
set num_lines = `wc -l $file | awk '{print $1}'`
@ num_timepoints = $num_lines - 14
tail -n $num_timepoints $file | awk '{print $1}' >t_stamps.txt


foreach i  (`seq 2 $num_timepoints`)
   
   set line2 = `head -n $i t_stamps.txt | tail -n 1`
   @ i = $i - 1
   set line1 = `head -n $i t_stamps.txt | tail -n 1`

   set line2_h = `echo $line2 | awk -F ":" '{print $1}'`
   set line2_m = `echo $line2 | awk -F ":" '{print $2}'`
   set line2_s = `echo $line2 | awk -F ":" '{print $3}' | awk -F "." '{print $1}'`

   set line2_ms = `echo $line2 | awk -F ":" '{print $3}' | awk -F "." '{print $2}'`
   set line1_h = `echo $line1 | awk -F ":" '{print $1}'`
   set line1_m = `echo $line1 | awk -F ":" '{print $2}'`
   set line1_s = `echo $line1 | awk -F ":" '{print $3}' | awk -F "." '{print $1}'`
   set line1_ms = `echo $line1 | awk -F ":" '{print $3}' | awk -F "." '{print $2}'`

   @ num_ms_2 = ($line2_h * 3600 + $line2_m * 60 + $line2_s) * 1000 + $line2_ms
   @ num_ms_1 = ($line1_h * 3600 + $line1_m * 60 + $line1_s) * 1000 + $line1_ms

   @ diff = $num_ms_2 - $num_ms_1
   
   if ($diff > 150) then
      echo $i $diff >> $output
    else if ($diff < 50 ) then
      echo $i $diff >>$output
  endif
end

echo $num_timepoints >>$output

rm -f t_stamps.txt
 


